NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.n2mi.n2med.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.n2mi.n2med.com-cert.pem
    OrganizationalUnitIdentifier: peer
