version: '2'

networks:
  n2med:

services:
  rca.n2med:
      container_name: rca.n2med.com
      image: hyperledger/fabric-ca:1.4.3
      command: sh -c 'fabric-ca-server start -d -b admin:adminpw --port 7054 --cfg.identities.allowremove'
      environment:
         - FABRIC_LOGGING_SPEC=grpc=debug:info        
         - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
         - FABRIC_CA_SERVER_CLIENT=/etc/hyperledger/fabric-ca-client
         - FABRIC_CA_CLIENT_TLS_CERTFILES=/etc/hyperledger/fabric-ca/tls-cert.pem
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_CA_NAME=rca.n2med.com
         - FABRIC_CA_SERVER_CSR_CN=rca.n2med.com
         - FABRIC_CA_SERVER_CSR_HOSTS=rca.n2med.com,${IP_ADDRESS}
         - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca/tlsca/rca.n2med-key.pem
         - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca/tlsca/rca.n2med-cert.pem
         - FABRIC_CA_SERVER_DEBUG=true
      volumes:
         - ./n2medCa/:/etc/hyperledger/fabric-ca
         - ./n2medCa/server:/etc/hyperledger/fabric-ca-server
         - ./n2medCa/client:/etc/hyperledger/fabric-ca-client
      ports:
         - 7054:7054
         
  orderer.n2med.com:
    container_name: orderer.n2med.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LEDGERTYPE=file
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      - FABRIC_CFG_PATH=/etc/hyperledger/ordererConfig
      # Enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.0.1:1443
    working_dir: /etc/hyperledger/
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderers/orderer.n2med.com/:/etc/hyperledger/orderer
        - ./ordererConfig:/etc/hyperledger/ordererConfig
    networks:
      - n2med

  orderer2.n2med.com:
    container_name: orderer2.n2med.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LEDGERTYPE=file      
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer2/msp
      - FABRIC_CFG_PATH=/etc/hyperledger/ordererConfig2
      # Enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer2/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer2/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer2/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer2/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer2/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/orderer2/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.0.1:1444
    working_dir: /etc/hyperledger/
    command: orderer
    ports:
      - 7060:7060
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderers/orderer2.n2med.com/:/etc/hyperledger/orderer2
        - ./ordererConfig2:/etc/hyperledger/ordererConfig2
    networks:
      - n2med

  orderer3.n2med.com:
    container_name: orderer3.n2med.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LEDGERTYPE=file      
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer3/msp
      - FABRIC_CFG_PATH=/etc/hyperledger/ordererConfig3
      # Enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer3/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer3/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer3/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer3/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer3/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/orderer3/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.0.1:1444
    working_dir: /etc/hyperledger/
    command: orderer
    ports:
      - 7070:7070
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderers/orderer3.n2med.com/:/etc/hyperledger/orderer3
        - ./ordererConfig3:/etc/hyperledger/ordererConfig3
    networks:
      - n2med

  peer0.n2med.com:
    container_name: peer0.n2med.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.n2med.com
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=N2miMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@peer0.n2med.com/msp
      - CORE_PEER_ADDRESS=peer0.n2med.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.n2med.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=n2mi_n2med
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCH_DB_USERNAME}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCH_DB_PASSWORD}
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/peers/peer0.n2med.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/peers/peer0.n2med.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/peers/peer0.n2med.com/tls/ca.crt
    working_dir: /etc/hyperledger/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/:/etc/hyperledger/peer
        - ./crypto-config/peerOrganizations/users:/etc/hyperledger/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.n2med.com
      - couchdb
    networks:
      - n2med

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=${COUCH_DB_USERNAME}
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
    ports:
      - 5984:5984
    networks:
      - n2med

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.n2med.com:7051
      - CORE_PEER_LOCALMSPID=N2miMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peerOrganizations/users/Admin@peer0.n2med.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peerOrganizations/peers/peer0.n2med.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peerOrganizations/peers/peer0.n2med.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peerOrganizations/peers/peer0.n2med.com/tls/ca.crt
    working_dir: /etc/hyperledger
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../../../fabric/chaincodes/med:/opt/med/
        - ./crypto-config/:/etc/hyperledger/
        - ./config:/etc/hyperledger/channel-artifacts
    networks:
        - n2med
    depends_on:
      - orderer.n2med.com
      - peer0.n2med.com
      - couchdb