Organizations:

        - &piccolo
                Name: piccoloMSP

                ID: piccoloMSP

                MSPDir: crypto-config/peerOrganizations/piccolo.com/msp

                AnchorPeers:
                        - Host: peer0.piccolo.com
                        - Port: 7052
