version: '2'

networks:
  n2med: 

services:
  ca:
    container_name: ca.${COMPANY_DOMAIN}
    image: hyperledger/fabric-ca
    command: sh -c 'fabric-ca-server start -d -b ${CA_ADMIN_USER}:${CA_ADMIN_PASSWORD} --tls.enabled --port 7150 -u https://admin:adminpw@${HOST_CA} --intermediate.tls.certfiles /etc/hyperledger/tls-certificates/tls-cert.pem --cfg.identities.allowremove'
    environment:
        - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
        - FABRIC_CA_SERVER_CLIENT=/etc/hyperledger/fabric-ca-client
        - FABRIC_CA_CLIENT_TLS_CERTFILES=/etc/hyperledger/fabric-ca/tls-cert.pem
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CA_NAME=ca.${COMPANY_DOMAIN}
        - FABRIC_CA_SERVER_CSR_HOSTS=ca.${COMPANY_DOMAIN}, ${HOST_IP}
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca/tlsca/ca.${ORGANIZATION_NAME_LOWERCASE}-key.pem
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca/tlsca/ca.${ORGANIZATION_NAME_LOWERCASE}-cert.pem
        - FABRIC_CA_SERVER_DEBUG=true
        - FABRIC_CA_ROOT_TLS=/etc/hyperledger/tls-certificates/tls-cert.pem
    volumes:
        - ./${ORGANIZATION_NAME}Ca/:/etc/hyperledger/fabric-ca
        - ./${ORGANIZATION_NAME}Ca/server:/etc/hyperledger/fabric-ca-server
        - ./${ORGANIZATION_NAME}Ca/client:/etc/hyperledger/fabric-ca-client
        - ./tls-certificates:/etc/hyperledger/tls-certificates
    ports:
        - 7150:7150

  orderer:
    container_name: orderer.alphamed.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/n2medchannel.block
      - ORDERER_GENERAL_LOCALMSPID=AlphamedOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      # Enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/etc/hyperledger/msp/orderer/tls/ca.crt
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/etc/hyperledger/msp/orderer/tls/ca.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
    working_dir: /opt/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderers/orderer.alphamed.com:/etc/hyperledger/msp/orderer
        - ./tls-certificates:/etc/hyperledger/tls-certificates       
    networks:
      - n2med

  peer:
    container_name: peer${PEER_NUMBER}.${COMPANY_DOMAIN}
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer${PEER_NUMBER}.${COMPANY_DOMAIN}
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=${ORGANIZATION_NAME}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@peer0.${COMPANY_DOMAIN}/msp
      - CORE_PEER_ADDRESS=peer${PEER_NUMBER}.${COMPANY_DOMAIN}:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer${PEER_NUMBER}.${COMPANY_DOMAIN}:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=n2mi_n2med
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.${COMPANY_DOMAIN}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCH_DB_USERNAME}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCH_DB_PASSWORD}
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/peer/tls/ca.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/peer/tls/server.key
    working_dir: /etc/hyperledger/configtx
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/peers/peer0.${COMPANY_DOMAIN}:/etc/hyperledger/peer
        - ./crypto-config/peerOrganizations/users:/etc/hyperledger/peer/users
        - ./config:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderers/orderer.alphamed.com/tls:/etc/hyperledger/peer/ordererTLS
        - ../../../fabric/chaincodes/med:/etc/hyperledger/chaincode/med/        
    depends_on:
      - orderer
      - couchdb
    networks:
      - n2med

  cli:
    container_name: cli.${COMPANY_DOMAIN}
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=grpc=debug:info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer${PEER_NUMBER}.${COMPANY_DOMAIN}:7051
      - CORE_PEER_LOCALMSPID=${ORGANIZATION_NAME}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/users/Admin@peer0.${COMPANY_DOMAIN}/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      # Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/peers/peer0.$COMPANY_DOMAIN/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/peers/peer0.$COMPANY_DOMAIN/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/peers/peer0.$COMPANY_DOMAIN/tls/ca.crt
    working_dir: /etc/hyperledger/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/etc/hyperledger/crypto-config
        - ./config:/etc/hyperledger/configtx
        - ../../../fabric/chaincodes/med:/etc/hyperledger/chaincode/med/        
    networks:
        - n2med

  couchdb:
    container_name: couchdb.${COMPANY_DOMAIN}
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=${COUCH_DB_USERNAME}
      - COUCHDB_PASSWORD=${COUCH_DB_PASSWORD}
    ports:
      - 5984:5984
    networks:
      - n2med